services:
  app:
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    depends_on:
      - mysqldb
    env_file: ./.env


  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - "$LOCAL_PORT:$DOCKER_PORT"
    env_file: ./.env